

<?php foreach($this->view->usuarios as $usuario_arr => $usuario) { ?>

    <div class="card-gestao">
        <form method="post" action="/aceitar-novo-esp">
            <div class="gestao-topico">
                <h3 class="nome-principal">Nome:<?= $usuario['nome'] ?></h3> 
            </div>
            <div class="gestao-topico">
            <h3 class="nome-principal"> Especialidade:<?= $usuario['especialidade'] ?></h3> 
            </div>
            <div class="gestao-topico">
                <h3 class="nome-principal"> Email:<?= $usuario['email'] ?></h3>
            </div>
            <div class="input-container">
                <label for="sigla" class="form-label nome-principal label-gestao">Sigla:</label>
                <input type="text" class="form-control form-gestao" id="sigla" name="sigla" required> 
            </div>

            
            <input type="hidden" name="id" value="<?= $usuario['id'] ?>">

            <button type="submit" class="btn btn-gestao-novo">Aceitar</button>
        </form>
    </div>
<?php } ?>

