<body>
    <input type="hidden" id="main-user-id" value="<?= $_SESSION['id'] ?>">
    <div class="container chat-box mt-4 ms-4">
        <div class="chat-header">
            <h2>Sistema de Chat</h2>
        </div>
        <div class="chat-body row">
            <div class="chat-contatos col-2">
            <?php foreach($this->view->usuarios as $usuario_arr => $usuario) { ?>
                <p class="nome-funcionario" data-id="<?= $usuario['id'] ?>">
                    <img class="img-user" src="/<?= $usuario['path_imagem'] ?>" >
                    <a><?= $usuario['nome'] ?></a>
                </p>
            <?php } ?>
            </div>
            <div class="col-8">
                <div class="chat-msg">
                    <div class="chat-perfil">
                        <h2 id="nome-usuario">Nome usuario</h2>
                        <div class="mensagens">

                        </div>
                    </div>
                    
                </div>
                <form id="form-chat" method="POST">
                    <textarea class="form-control chat-text" id="texto-chat" rows="3"></textarea>
                    <input type="submit" class="btn btn-primary" value="Enviar">
                </form>
            </div>

        </div>

    </div>


    <script>

        $(document).ready(function() {
            $('.nome-funcionario').click(function() {
                var OtherUser = $(this).data('id');
                var mainUser = $('#main-user-id').val();

                $.ajax({
                    url: '/nova-conversa',
                    method: 'POST',
                    data: { OtherUser: OtherUser,
                            mainUser: mainUser},
                    success: function(response) {
                        var conversa = JSON.parse(response);
                        var mensagensDiv = $('.chat-msg .mensagens');

                        var nomeUsuario = conversa.otherUser;
                        $('#nome-usuario').text(nomeUsuario);

                        conversa.mensagens.forEach(function(mensagem) {
                            var htmlMensagem = '<div><strong>' + nomeUsuario + ':</strong> ' + mensagem.texto + '</div>';
                            mensagensDiv.append(htmlMensagem);
                        });

                    },
                    error: function() {
                        alert('Ocorreu um erro ao buscar o usuário.');
                    }
                });
            });
        });


    </script>


</body>
</html>
