<div class="container mt-4">
    <div class="card">
        <div class="card-header">
            <h4>Configurações</h4>
        </div>
        <div class="card-body">
            <h6>Trocar senha</h6>
            <form method="post" action="/trocar">
                <div class="mb-3 row">
                    <label for="oldpass" class="col-sm-2 col-form-label">Senha antiga:</label>
                    <div class="col-sm-4">
                        <input type="password" class="form-control" id="oldpass">
                    </div>
                </div>

                <div class="mb-3 row">
                    <label for="newpass" class="col-sm-2 col-form-label">Senha nova:</label>
                    <div class="col-sm-4">
                        <input type="password" class="form-control" id="newpass">
                    </div>
                </div>
                <?php echo $_SESSION['email'] ?>
                <button type="submit" class="btn btn-primary">Submit</button>
            </form>    
        </div>
    </div>
</div>