
<div class="container" style="width:750px">
    <div class="card mt-4">
        <div class="card-header">
            <div class="row">
                <div class="col">
                    <h3>Funcionários</h3>
                </div>
            </div>
        </div>
        <div class="card-body">
            <table class="table text-center">
                <thead>
                    <tr>
                        <th scope="col"><h6>Nome</h6></th>
                        <th scope="col"><h6>Email</h6></th>
                        <th scope="col"><h6>Especialidade</h6></th>
                        <th scope="col"><h6>Excluir</h6></th>
                        <th scope="col"><h6>Aceitar</h6></th>    
                    <tr>
                </thead>
                <tbody>
                <?php foreach($this->view->usuarios as $indice => $usuarios){ ?>
                    <tr>
                        <td scope="col"><h6><?= $usuarios['nome'] ?></h6></td>
                        <td scope="col"><h6><?= $usuarios['email'] ?></h6></td>
                        <td scope="col"><h6><?= $usuarios['especialidade'] ?></h6></td>
                    </tr>
                    
                 <?php } ?>     
                </tbody>
            </table>
        </div>
        
    </div>

</div>
