<!-- Incluir a biblioteca do Google Charts -->
<script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>


<!-- Incluir o código JavaScript -->
<script type="text/javascript">
  // Função para desenhar o gráfico
  function drawChart() {
    // Dados para o gráfico
    var data = google.visualization.arrayToDataTable([
      ['Mês', 'Valor Bruto', 'Valor Ivestido', 'Valor Liquido'],
      <?php foreach($this->view->graficos as $grafico_arr => $grafico) { ?>
        ['<?= $grafico['data_mes'] ?>',  <?= $grafico['soma_total_receita_bruta'] ?>, <?= $grafico['soma_total_investido'] ?>, <?= $grafico['total_liquido'] ?>],
      <?php } ?>
    ]);

    // Opções do gráfico
    var options = {
      title: 'Valores Mensais',
      curveType: 'function',
      legend: { position: 'bottom' },
    };

    // Criar o gráfico
    var chart = new google.visualization.LineChart(document.getElementById('curve_chart'));

    // Desenhar o gráfico
    chart.draw(data, options);
  }

  // Carregar a biblioteca do Google Charts
  google.charts.load('current', {'packages':['corechart']});

  // Chamar a função drawChart após a biblioteca ser carregada
  google.charts.setOnLoadCallback(drawChart);
</script>

<div class="container mt-3">
    <div class="container d-flex justify-content-center">
        <table class="tabela-topo">
            <tr>
                <th></th>
                <th>Total</th>
                <th>Parceria Studby</th>
                <th>Parceria Pessoal</th>   
            </tr>
            <tr>
                <th>Total Bruto</th>
                <?php $this->view->usuarios  ?>
                    <th>R$ <?= $this->view->usuarios[0]['soma_total_receita_bruta'] ?>,00</th>
                    <th>R$ <?= $this->view->usuarios[0]['soma_receita_por_fonte_1'] ?>,00</th>
                    <th>R$ <?= $this->view->usuarios[0]['soma_receita_por_fonte_2'] ?>,00</th>

            <tr>
                <th>Total Investido</th>
                <?php $this->view->usuarios  ?>
                    <th>R$ <?= $this->view->usuarios[0]['soma_total_investido'] ?>,00</th>
                    <th>R$ <?= $this->view->usuarios[0]['soma_oferta_1'] ?>,00</th>
                    <th>R$ <?= $this->view->usuarios[0]['soma_oferta_2'] ?>,00</th>
            <tr>
            <tr>
                <th>Total Liquido</th>
                <?php $this->view->usuarios  ?>
                    <th>R$ <?= $this->view->usuarios[0]['diferenca_total'] ?>,00</th>
                    <th>R$ <?= $this->view->usuarios[0]['total_1'] ?>,00</th>
                    <th>R$ <?= $this->view->usuarios[0]['total_2'] ?>,00</th>
            <tr>
        </table>

        <table>
            <tr>
                <th>Clientes ativos</th>
                <th><?= $this->view->usuarios[0]['status_ativos'] ?></th>  
            </tr>
            <tr>
                <th>Enviado</th>
                <th><?= $this->view->usuarios[0]['status_enviado'] ?></th> 
            </tr>
            <tr>
                <th>Fazendo</th>
                <th><?= $this->view->usuarios[0]['status_fazendo'] ?></th> 
            </tr>
            <tr>
                <th>Entregue</th>
                <th><?= $this->view->usuarios[0]['status_entregue'] ?></th> 
            </tr>
            <tr>
                <th>Garantia</th>
                <th><?= $this->view->usuarios[0]['status_garantia'] ?></th> 
            </tr>
            <tr>
                <th>Revisão</th>
                <th><?= $this->view->usuarios[0]['status_revisão'] ?></th> 
            </tr>
            <tr>
                <th>Total</th>
                <th><?= $this->view->usuarios[0]['status_todos'] ?></th> 
            </tr>
        </table>
    </div>


    <div class="container d-flex justify-content-center">

        <table class="mt-4 ">
            <tr>
                <th></th>
                <?php foreach($this->view->usuarios as $usuario_arr => $usuario) { ?>
                    <th><?= $usuario['nome'] ?></th>
                <?php } ?>
            <tr>
            <tr>
                <th>Receita Bruta</th>
                <?php foreach($this->view->usuarios as $usuario_arr => $usuario) { ?>
                    <th>R$ <?= $usuario['total_receita_bruta'] ?>,00</th>
                <?php } ?>
            <tr>
            <tr>
                <th>Total Investido</th>
                <?php foreach($this->view->usuarios as $usuario_arr => $usuario) { ?>
                    <th>R$ <?= $usuario['total_investido'] ?>,00</th>
                <?php } ?>
            <tr>
            <tr>
                <th>Total Liquido</th>
                <?php foreach($this->view->usuarios as $usuario_arr => $usuario) { ?>
                    <th>R$ <?= $usuario['diferenca'] ?>,00</th>
                <?php } ?>
            <tr>
            <tr>
                <th>Pedido(1)</th>
                <?php foreach($this->view->usuarios as $usuario_arr => $usuario) { ?>
                    <th><?= $usuario['status_1'] ?></th>
                <?php } ?>
            <tr>
            <th>Fazendo(2)</th>
                <?php foreach($this->view->usuarios as $usuario_arr => $usuario) { ?>
                    <th><?= $usuario['status_2'] ?></th>
                <?php } ?>
            <tr>
            <th>Entregue(3)</th>
                <?php foreach($this->view->usuarios as $usuario_arr => $usuario) { ?>
                    <th><?= $usuario['status_3'] ?></th>
                <?php } ?>
            <tr>
            <th>Garantia(4)</th>
                <?php foreach($this->view->usuarios as $usuario_arr => $usuario) { ?>
                    <th><?= $usuario['status_4'] ?></th>
                <?php } ?>
            <tr>
            <th>Revisão(5)</th>
                <?php foreach($this->view->usuarios as $usuario_arr => $usuario) { ?>
                    <th><?= $usuario['status_5'] ?></th>
                <?php } ?>
            <tr>
            <th>Concluido(6)</th>
                <?php foreach($this->view->usuarios as $usuario_arr => $usuario) { ?>
                    <th><?= $usuario['status_6'] ?></th>
                <?php } ?>
            <tr>
        </table>
        
    </div>  

    <!-- Div para o gráfico -->
    <div id="curve_chart" style="width: 1200px; height: 300px;">
    </div>

</div>





