<div class="container mt-4">
    <div class="card">
        <div class="card-header">
            <h4>Formulário Principal</h4>
        </div>
        <div class="card-body">
            <form method="post" action="/criar_pedido">
                <div class="mb-3">
                    <label for="titulo" class="form-label">Titulo</label>
                    <input type="text" class="form-control" id="titulo" name="titulo" placeholder="Digite o titulo aqui">
                </div>
                <div class="row mb-3">
                    <div class="col">
                        <label for="receita_bruta" class="form-label">Receita bruta</label>
                        <input type="number" class="form-control" id="receita_bruta" name="receita_bruta" placeholder="Digite a receita bruta aqui">
                    </div>
                    <div class="col">
                        <label for="prazo_real" class="form-label">Prazo real</label>
                        <input type="date" class="form-control" id="prazo_real" name="prazo_real" placeholder="Digite o prazo real">
                    </div>
                    <div class="col">
                        <label for="fonte" class="form-label">Fonte</label>
                        <select name="fonte" id="fonte" class="form-select" aria-label="Default select example">
                        <option value="1" selected>Studybay</option>
                            <option value="2">Pessoal</option>
                        </select>
                    </div>
                    <div class="col">
                        <label for="oferta" class="form-label">Oferta</label>
                        <input type="number" class="form-control" id="oferta" name="oferta" placeholder="Digite o valor da oferta aqui">
                    </div>
                </div>

                <div class="row mb-3">

                    <div class="col">
                        <label for="paginas" class="form-label">Número de paginas</label>
                        <input type="number" class="form-control" id="paginas" name="paginas" placeholder="Digite o numero de paginas">
                    </div>
                    <div class="col">
                        <label for="id_usuario" class="form-label">Especialista</label>
                        <select name="id_usuario" id="id_usuario" class="form-select" aria-label="Default select example">
                        <?php foreach($this->view->usuarios as $indice => $usuarios){ ?>
                        <option value="<?= $usuarios['id'] ?>"><?= $usuarios['nome'] ?></option>
                        <?php } ?>
                        </select>
                    </div>
                    <div class="col">
                        <label for="disciplina" class="form-label">Disciplina</label>
                        <input type="text" class="form-control" id="disciplina" name="disciplina" placeholder="Digite a disciplina aqui">
                    </div>
                    <div class="col">
                        <label for="tipo" class="form-label">Tipo de trabalho</label>
                        <input type="text" class="form-control" id="tipo" name="tipo" placeholder="Digite o tipo de trabalho">
                    </div>
                </div>

                <div class="row mb-3">
                    <div class="col">
                        <label for="metodologia" class="form-label">Metodologia</label>
                        <input type="text" class="form-control" id="metodologia" name="metodologia" placeholder="Digite a metodologia aqui">
                    </div>
                    <div class="col">
                        <label for="arquivos" class="form-label">Arquivos do cliente</label>
                        <input type="text" class="form-control" id="arquivos" name="arquivos" placeholder="Coloque o link dos arquivos aqui">
                    </div>
                    <div class="col">
                        <label for="prazo_entrega" class="form-label">Prazo de entrega</label>
                        <input type="date" class="form-control" id="prazo_entrega" name="prazo_entrega" placeholder="Digite o prazo de entrega">
                    </div>

                    <div class="col">
                        <label for="prazo_garantia" class="form-label">Prazo de garantia</label>
                        <input type="date" class="form-control" id="prazo_garantia" name="prazo_garantia" placeholder="Digite o prazo de garantia">
                    </div>
                </div>

                <div class="row mb-3">
                    <div class="col">
                        <label for="tema" class="form-label">Tema</label>
                        <input type="text" class="form-control" id="tema" name="tema" placeholder="Digite o tema aqui">
                    </div>
                    <div class="col">
                        <label for="descricao" class="form-label">Descricao</label>
                        <input type="text" class="form-control" id="descricao" name="descricao" placeholder="Descreva o trabalho aqui">
                    </div>
                    <div class="col">
                        <label for="observacao" class="form-label">Observacao</label>
                        <input type="text" class="form-control" id="observacao" name="observacao" placeholder="Digite a observação aqui">
                    </div>
                </div>

                <button type="submit" class="btn btn-primary">Confirmar</button>
            </form> 
        </div>
    </div>
</div>