<?php 

$pedido = $this->view->pedidos;


?>
<a type="button" href="/visualizar" class="btn btn-light">Voltar</a>
<div class="container meio mt-3">
    <div class="card">
        <h5 class="card-header">Pedido: <?= $pedido['titulo'] ?></h5>
            <div class="card-body">
                <form method="post" action="/trocar_especialista">
                    
                    <input type="hidden" name="id" value="<?= $pedido['id'] ?>">

                    <label for="id_usuario" class="form-label">Especialista</label>
                            <select name="id_usuario" id="id_usuario" class="form-select" aria-label="Default select example">
                            <?php foreach($this->view->usuarios as $indice => $usuarios){ ?>
                            <option value="<?= $usuarios['id'] ?>"><?= $usuarios['nome'] ?></option>
                            <?php } ?>
                    </select>
                    
                    <button type="submit" class="btn btn-primary">Confirmar</button>
                </form>
            </div>
    </div>
</div>  



                    
                  




    
 

