<div class="container mt-3">
    <table class="tabelas">
        <thead>
            <tr>
                <th>Reg.</th>
                <th>S/N</th>
                <th>Garantia</th>
                <th>Real</th>
                <th>Entrega</th>
                <th>Estado</th>
                <th>Est/Num</th>
                <th >Nome dos Pedidos</th>
                <th>Bruto</th>
                <th>Invest. </th>
                <th>Lucro</th>
                <th>Lauda</th>
                <th>Esp.</th>
                <th>Pago</th>
                <th>Recibo</th>
                <th>Diretório</th>
                <th>Observações</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach($this->view->pedidos as $pedido_arr => $pedido) { ?>
                <tr>
                    <td><?= $pedido['id'] ?></td>
                    <td class="fonte"><?= $pedido['fonte'] ?></td>
                    <td><?= $pedido['prazo_garantia'] ?></td>
                    <td><?= $pedido['prazo_real'] ?></td>
                    <td><?= $pedido['prazo_entrega'] ?></td>

                    
                    <td class="status" data-value="<?= $pedido['status'] ?>">
                        <?php if ($pedido['status'] == 6) { ?>
                            <a href="novo_especialista?id=<?= $pedido['id'] ?>"><?= $pedido['status'] ?></a>
                        <?php } else { ?>
                            <?= $pedido['status'] ?>
                        <?php } ?>
                    </td>

                    <td class="numero" data-value="<?= $pedido['status'] ?>">
                        <?php if ($pedido['status'] == 6) { ?>
                            <a href="novo_especialista?id=<?= $pedido['id'] ?>"><?= $pedido['status'] ?></a>
                        <?php } else { ?>
                            <?= $pedido['status'] ?>
                        <?php } ?>
                    </td>

                    <td class="titulo"><?= $pedido['titulo'] ?></td>
                    <td><?= $pedido['receita_bruta'] ?></td>
                    <td><?= $pedido['oferta'] ?></td>
                    <td class="resultado"></td>
                    <td><?= $pedido['paginas'] ?></td>

                    <td class="nome" data-value="<?= $pedido['usuario_nome'] ?>">
                        <?php if ($pedido['usuario_nome'] == "Nenhum") { ?>
                            <a href="novo_especialista?id=<?= $pedido['id'] ?>">Nenhum</a>
                        <?php } else { ?>
                            <?= $pedido['usuario_nome'] ?>
                        <?php } ?>
                    </td>

                    <td><?= $pedido['pagamento'] ?></td>
                    <td><?= $pedido['fonte'] ?></td>
                    <td><?= $pedido['fonte'] ?></td>
                    <td><a href="pedido_visu_adm?id=<?= $pedido['id'] ?>&id_usuario=<?= $pedido['id_usuario'] ?>">Inf</td>
                </tr>
            <?php } ?>
        </tbody>
    </table>
</div>

<script>

    function manipularEntrega(){
        var cells = document.querySelectorAll('.entrega');

        // percorre todas as células da tabela
        for (var i = 0; i < cells.length; i++) {
            var cell = cells[i];

        // verifica se o conteúdo da célula é igual a 1 ou 2
            if (cell.innerHTML == '1') {
                cell.innerHTML = 'N'; // substitui por "N"
                cell.classList.add('n'); // adiciona classe "n"
            } else if (cell.innerHTML == '2') {
                cell.innerHTML = 'S'; // substitui por "S"
                cell.classList.add('s'); // adiciona classe "s"
            }
        }
    }

    function manipularFonte(){
        var cells = document.querySelectorAll('.fonte');

        // percorre todas as células da tabela
        for (var i = 0; i < cells.length; i++) {
        var cell = cells[i];

        // verifica se o conteúdo da célula é igual a 1 ou 2
            if (cell.innerHTML == '1') {
                cell.innerHTML = 'S'; // substitui por "N"

            } else if (cell.innerHTML == '2') {
                cell.innerHTML = 'N'; // substitui por "S"

            }
        }
    }

    function valorLucro(){
        // Seleciona todas as linhas da tabela
        const rows = document.querySelectorAll("table tbody tr");
  
        // Loop pelas linhas e calcula a subtração dos valores
        rows.forEach((row) => {
            // Seleciona as células das colunas "valor 1" e "valor 2"
            const valor1 = parseInt(row.querySelector("td:nth-child(9)").textContent);
            const valor2 = parseInt(row.querySelector("td:nth-child(10)").textContent);
            
            // Calcula a subtração dos valores
            const resultado = valor1 - valor2;
            
            // Exibe o resultado na célula da coluna "resultado"
            row.querySelector(".resultado").textContent = resultado;
        });
    }

    function corStatus() {

        var cells = document.querySelectorAll('.status');
        for (var i = 0; i < cells.length; i++) {
            var cell = cells[i];
            var status = cell.getAttribute('data-value');
            var nome = cell.parentNode.querySelector('.nome').getAttribute('data-value');

            if(nome === 'Nenhum') {
                if (status === '0'){
                    cell.innerHTML = 'Nada';
                }
            } else if(status === '0') {
                cell.innerHTML = 'Enviado';
                cell.classList.add('rosa');

            } else if(status === '1') {
                cell.innerHTML = 'Fazendo';
                cell.classList.add('laranja');

            } else if(status === '2') {
                cell.innerHTML = 'Garantia';
                cell.classList.add('azul');
            }

            else if(status === '3') {
                cell.innerHTML = 'Revisando';
                cell.classList.add('vermelho');
            }

            else if(status === '4') {
                cell.innerHTML = 'Pago';
                cell.classList.add('verde');
            }

            else if(status === '6') {
                cell.innerHTML = 'Retorno';
                cell.classList.add('roxo');
            }
        }
    }

    function numeroStatus() {

        var cells = document.querySelectorAll('.numero');
        for (var i = 0; i < cells.length; i++) {
            var cell = cells[i];
            var numero = cell.getAttribute('data-value');
            var nome = cell.parentNode.querySelector('.nome').getAttribute('data-value');

            if(nome === 'Nenhum') {
                if (numero === '0'){
                    cell.innerHTML = '0';
                }
            } else if(numero === '0') {
                cell.innerHTML = '1';

            } else if(numero === '1') {
                cell.innerHTML = '2';

            } else if(numero === '2') {
                cell.innerHTML = '3';
            }

            else if(numero === '3') {
                cell.innerHTML = '4';
            }

            else if(numero === '4') {
                cell.innerHTML = '5';
            }
        }

    }

    manipularEntrega();
    manipularFonte();
    valorLucro();
    corStatus();
    numeroStatus();

</script>