<div class="container mt-3">
    <table class="tabelas">
        <thead>
            <tr>
                <th>Reg.</th>
                <th>S/N</th>
                <th>Garantia</th>
                <th>Real</th>
                <th>Entrega</th>
                <th>Entregue</th>
                <th>Estado</th>
                <th >Nome dos Pedidos</th>
                <th>Bruto</th>
                <th>Invest. </th>
                <th>Lucro</th>
                <th>Lauda</th>
                <th>Esp.</th>
                <th>Pago</th>
                <th>Recibo</th>
                <th>Diretório</th>
                <th>Observações</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach($this->view->pedidos as $pedido_arr => $pedido) { ?>
                <tr>
                    <td><?= $pedido['id'] ?></td>
                    <td class="fonte"><?= $pedido['fonte'] ?></td>
                    <td><?= $pedido['prazo_garantia'] ?></td>
                    <td><?= $pedido['prazo_real'] ?></td>
                    <td><?= $pedido['prazo_entrega'] ?></td>
                    <td class="entrega"><?= $pedido['entregue'] ?></td>
                    
                    <td>
                        <?php if( $pedido['status'] == 6){ ?>
                    
                            <a href="/novo_especialista?id=<?= $pedido['id'] ?>"> <?= $pedido['status'] ?></a>
                                
                            <?php } else { ?>
                                <?= $pedido['status'] ?>
                        <?php } ?>
                
                    </td>
                    <td class="titulo"><?= $pedido['titulo'] ?></td>
                    <td><?= $pedido['receita_bruta'] ?></td>
                    <td><?= $pedido['oferta'] ?></td>
                    <td class="resultado"></td>
                    <td><?= $pedido['paginas'] ?></td>
                    <td><?= $pedido['usuario_nome'] ?></td>
                    <td><?= $pedido['pagamento'] ?></td>
                    <td><?= $pedido['fonte'] ?></td>
                    <td><?= $pedido['fonte'] ?></td>
                    <td><?= $pedido['observacao'] ?></td>
                </tr>
            <?php } ?>
        </tbody>
    </table>
</div>

<script>

    function manipularEntrega(){
        var cells = document.querySelectorAll('.entrega');

        // percorre todas as células da tabela
        for (var i = 0; i < cells.length; i++) {
            var cell = cells[i];

        // verifica se o conteúdo da célula é igual a 1 ou 2
            if (cell.innerHTML == '1') {
                cell.innerHTML = 'N'; // substitui por "N"
                cell.classList.add('n'); // adiciona classe "n"
            } else if (cell.innerHTML == '2') {
                cell.innerHTML = 'S'; // substitui por "S"
                cell.classList.add('s'); // adiciona classe "s"
            }
        }
    }

    function manipularFonte(){
        var cells = document.querySelectorAll('.fonte');

        // percorre todas as células da tabela
        for (var i = 0; i < cells.length; i++) {
        var cell = cells[i];

        // verifica se o conteúdo da célula é igual a 1 ou 2
            if (cell.innerHTML == '1') {
                cell.innerHTML = 'S'; // substitui por "N"

            } else if (cell.innerHTML == '2') {
                cell.innerHTML = 'N'; // substitui por "S"

            }
        }
    }

    function valorLucro(){
        // Seleciona todas as linhas da tabela
        const rows = document.querySelectorAll("table tbody tr");
  
        // Loop pelas linhas e calcula a subtração dos valores
        rows.forEach((row) => {
            // Seleciona as células das colunas "valor 1" e "valor 2"
            const valor1 = parseInt(row.querySelector("td:nth-child(9)").textContent);
            const valor2 = parseInt(row.querySelector("td:nth-child(10)").textContent);
            
            // Calcula a subtração dos valores
            const resultado = valor1 - valor2;
            
            // Exibe o resultado na célula da coluna "resultado"
            row.querySelector(".resultado").textContent = resultado;
        });
    }

    // function statusNegativo(){
    //     var cells = document.querySelectorAll('.status');

    //     // percorre todas as células da tabela
    //     for (var i = 0; i < cells.length; i++) {
    //         var cell = cells[i];

    //         if (cell.innerHTML == '6') {
    //             cell.innerHTML = 'N'; // substitui por "N"
    //             cell.classList.add('roxo'); // adiciona classe "roxo"
    //         }
    //     }
    // }

    manipularEntrega()
    manipularFonte()
    valorLucro()
    statusNegativo()

</script>