<html>

<head>
	<meta charset="utf-8" />
	<title>Projeto A</title>


	<link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css"
		integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous" />
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet"
		integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
	<script src="https://kit.fontawesome.com/2621a537e3.js" crossorigin="anonymous"></script>
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.0/jquery.min.js"></script>
	<link rel="stylesheet" href="/css/style.css" />

	<script src="https://cdn.jsdelivr.net/npm/fullcalendar@6.1.8/index.global.min.js"></script>






</head>

<body>
<?php

if (!isset($_SESSION)) 
{
    session_start();

    if($_SESSION['tipo'] != 1){
        header('Location: /');  
    }
}


?>
<nav class="head-principal navbar navbar-expand-lg">
  <div class="container-fluid">
    <!-- Ícone no canto esquerdo -->
    <a class="navbar-brand" href="/adm/home">
      <img src="/img/logo.jpeg" alt="Logo" style="width: 80px;">
	  <span class="logo-index-desc">Consultoria Acadêmica</span>
    </a>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
      aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link principal-configurar" href="/adm/configurar">
            <img style="width: 30px" src="/img/config.png">
            <!-- &nbsp;<?php echo $_SESSION['nome'] ?> -->
          </a>
        </li>
        <li class="nav-item">
          <a  class="nav-link principal-configurar" href="/sair">
		  	<img style="width: 30px" src="/img/sair.png">
		  </a>
        </li>
		<li class="nav-item">
			<span class="span-baixo">
				Suporte@supertcc.com
				© 2017 SuperTCC. CNPJ: 42.976.9700001-77
			</span>
		</li>
      </ul>
    </div>

	

  </div>
</nav>


	<div class="lista-lateral">
		<div class="foto">					
			<img class="centered-image" src="/<?php echo $_SESSION['path_imagem'] ?>" style="width: 140px;" alt="Imagem do usuário">		
		</div>
		<ul class="form-lateral">
			<li class="lista principal">
				<img class="icone-principal" src="/img/casa.png" alt="Ícone 1">
				<a class="link" href="/adm/home">Home</a>
			</li>
			<li class="lista principal">
			<img class="icone-principal" src="/img/mais.png" alt="Ícone 1">
				<a class="link" href="/criacao">Add pedido</a>
			</li>
			<li class="lista principal">
			<img class="icone-principal" src="/img/calendario.png" alt="Ícone 1">
				<a class="link" href="/adm/calendario">Calendario</a>
			</li>
			<li class="lista principal">
			<img class="icone-principal" src="/img/olho.png" alt="Ícone 1">
				<a class="link" href="/visualizar">Pedidos</a>
			</li>
			<li class="lista principal">
			<img class="icone-principal" src="/img/chat.png" alt="Ícone 1">
				<a class="link" href="/adm/chat">Mensagens</a>
			</li>
			<li class="lista principal">
			<img class="icone-principal" src="/img/gestao.png" alt="Ícone 1">
				<a class="link" href="/adm/gestao">Gestão</a>
			</li>
			
		</ul>
	</div>

	<div style="position:absolute;left: 200px">
		<?= $this->content() ?>
	</div>



	<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"
		integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN"
		crossorigin="anonymous">
	</script>
</body>

</html>