<div class="container mt-5 bg-dark-subtle rounded-3" style="width: 400px; height:320px; opacity: 75%">
  <form method="post" action="/autenticar">
    <div class="pt-2">
      <h2>Login</h2>
      <hr>
    </div>
    <div class="mb-2 pt-2">
      <label for="email" class="form-label">Email:</label>
      <input type="email" name="email" class="form-control" id="email" placeholder="Email">
    </div>
    <div class="mb-3">
      <label for="senha" class="form-label">Password:</label>
      <input type="password" name="senha" class="form-control" id="senha" placeholder="Senha">
    </div>
      <button type="submit" class="btn btn-primary">Confirmar</button>
      <a type="button" href="/registro" class="btn btn-primary">Registrar</a>
      
			<?php if($this->view->login == 'erro') { ?>
			<div class="row">
				<div class="col">
					<span class="text text-danger">*E-mail ou senhas inválido(s)</span>
				</div>
			</div>
			<?php } ?>

  </form>
</div>

