
<div class="logo">
  <img src="img/logo.jpeg"  class="logo-index" alt="Logo da Empresa">
</div>


<div class="container mt-5 fundo-index" >
  <form method="post" action="/autenticar">
    <div class="pt-2">

    <div class="mb-2 pt-2">
      <input type="email" name="email" class="form-control input-index" id="email" placeholder="Email">
    </div>
    <div class="mb-3">
      <input type="password" name="senha" class="form-control input-index" id="senha" placeholder="Senha">
    </div>
    <div class="mb-3 d-flex justify-content-center align-items-center"> <!-- Adicione uma margem inferior para separar o campo de senha e a opção Lembrar-me -->
        <div class="form-check">
          <input type="checkbox" class="form-check-input" id="lembrar">
          <label class="form-check-label" for="lembrar">Lembrar-me</label>
        </div>
      </div>
      <div class="d-flex justify-content-center align-items-center">
        <button type="submit" class="btn-index">Confirmar</button>
        <a type="button" href="/registro" class="btn-index ms-2">Registrar</a>
      </div>
      
			<?php if($this->view->login == 'erro') { ?>
			<div class="row">
				<div class="col">
					<span class="text text-danger">*E-mail ou senhas inválido(s)</span>
				</div>
			</div>
			<?php } ?>

  </form>
</div>

