<?php
$pedido = $this->view->pedidos;


?>

<div class="container mt-4">
    <div class="card">
        <div class="card-header">
            <h4>Formulário Principal</h4>
        </div>
        <div class="card-body">
            <form method="post" action="/atualizar_pedido">

            <div class="mb-3">
                <label for="id" class="form-label"></label>
                <input type="hidden" class="form-control" id="id" name="id" value="<?= $pedido['id'] ?>">
            </div>
                <div class="mb-3">
                    <label for="titulo" class="form-label">Titulo</label>
                    <input type="text" class="form-control" id="titulo" name="titulo" value="<?= $pedido['titulo'] ?>">
                </div>
                <div class="row mb-3">
                    <div class="col">
                        <label for="receita_bruta" class="form-label">Receita bruta</label>
                        <input type="number" class="form-control" id="receita_bruta" name="receita_bruta" value="<?= $pedido['receita_bruta'] ?>">
                    </div>
                    <div class="col">
                        <label for="prazo_real" class="form-label">Prazo real</label>
                        <input type="date" class="form-control" id="prazo_real" name="prazo_real"  value="<?= date('Y-m-d', strtotime($pedido['prazo_real'])) ?>">
                    </div>
                    <div class="col">
                        <label for="fonte" class="form-label">Fonte</label>
                        <select name="fonte" id="fonte" class="form-select" aria-label="Default select example">
                        <option value="1" selected>Studybay</option>
                            <option value="2">Pessoal</option>
                        </select>
                    </div>
                    <div class="col">
                        <label for="oferta" class="form-label">Oferta</label>
                        <input type="number" class="form-control" id="oferta" name="oferta" value="<?= $pedido['oferta'] ?>">
                    </div>
                </div>

                <div class="row mb-3">

                    <div class="col">
                        <label for="paginas" class="form-label">Número de paginas</label>
                        <input type="number" class="form-control" id="paginas" name="paginas" value="<?= $pedido['paginas'] ?>">
                    </div>
                    <div class="col">
                        <label for="id_usuario" class="form-label">Especialista</label>
                            <select name="id_usuario" id="id_usuario" class="form-select" aria-label="Default select example">
                                <?php foreach($this->view->usuarios as $indice => $usuarios){ ?>
                                    <option value="<?= $usuarios['id'] ?>"><?= $usuarios['nome'] ?></option>
                                <?php } ?>
                            </select>
                    </div>
                    <div class="col">
                        <label for="disciplina" class="form-label">Disciplina</label>
                        <input type="text" class="form-control" id="disciplina" name="disciplina" value="<?= $pedido['disciplina'] ?>">
                    </div>
                    <div class="col">
                        <label for="tipo" class="form-label">Tipo de trabalho</label>
                        <input type="text" class="form-control" id="tipo" name="tipo" value="<?= $pedido['tipo'] ?>">
                    </div>
                </div>

                <div class="row mb-3">
                    <div class="col">
                        <label for="metodologia" class="form-label">Metodologia</label>
                        <input type="text" class="form-control" id="metodologia" name="metodologia" value="<?= $pedido['metodologia'] ?>">
                    </div>
                    <div class="col">
                        <label for="arquivos" class="form-label">Arquivos do cliente</label>
                        <input type="text" class="form-control" id="arquivos" name="arquivos" value="<?= $pedido['arquivos'] ?>">
                    </div>
                    <div class="col">
                        <label for="prazo_entrega" class="form-label">Prazo de entrega</label>
                        <input type="date" class="form-control" id="prazo_entrega" name="prazo_entrega" value="<?= date('Y-m-d', strtotime($pedido['prazo_entrega'])) ?>">
                    </div>

                    <div class="col">
                        <label for="prazo_garantia" class="form-label">Prazo de garantia</label>
                        <input type="date" class="form-control" id="prazo_garantia" name="prazo_garantia" value="<?= date('Y-m-d', strtotime($pedido['prazo_garantia'])) ?>">
                    </div>
                </div>

                <div class="row mb-3">
                    <div class="col">
                        <label for="tema" class="form-label">Tema</label>
                        <input type="text" class="form-control" id="tema" name="tema" value="<?= $pedido['temas'] ?>">
                    </div>
                    <div class="col">
                        <label for="descricao" class="form-label">Descricao</label>
                        <input type="text" class="form-control" id="descricao" name="descricao" value="<?= $pedido['descricao'] ?>">
                    </div>
                    <div class="col">
                        <label for="observacao" class="form-label">Observacao</label>
                        <input type="text" class="form-control" id="observacao" name="observacao" value="<?= $pedido['observacao'] ?>">
                    </div>

                </div>

                
                <div class="col mb-3">
                        <label for="corpo" class="form-label">Corpo do trabalho</label>
                        <textarea class="form-control" id="corpo" name="corpo" value="<?= $pedido['corpo'] ?>"  rows="6">              
                        </textarea>
                </div>  

                <button type="submit" class="btn btn-primary">Confirmar</button>
            </form> 
        </div>
    </div>
</div>  