<div class="lista-lateral">
		<div class="foto">
			    <?php foreach($this->view->usuario as $usuario_arr => $usuario) { ?>
                	<img src=" <?= $usuario['path_imagem'] ?> " class="centered-image"   alt="Imagem do usuário">
				<?php } ?>
        </div>
		<ul class="form-lateral">
			<li class="lista principal"><a class="link" href="/esp/home">Home</a></li>
			<li hr class="lista principal"><a class="link" href="/esp/pedidos">Pedidos</a></li>
			<li class="lista principal">Mensagens</li>
			<li class="lista principal"><a class="link" href="/esp/calendario">Calendario</a></li>
		</ul>
</div>

<div class="container mt-4"   style="width: 1000px;">
    <div class="card">
        <div class="card-header">
            <h4>Configurações</h4>
        </div>
        <div class="card-body">
            <h5>Trocar Senha</h5>
            <hr>
            <form method="post" action="/trocar" class="mb-5">
                <div class="mb-3 row">
                    <label for="oldpass" class="col-sm-2 col-form-label">Senha antiga:</label>
                    <div class="col-sm-4">
                        <input type="password" class="form-control" id="oldpass">
                    </div>
                </div>

                <div class="mb-3 row">
                    <label for="newpass" class="col-sm-2 col-form-label">Senha nova:</label>
                    <div class="col-sm-4">
                        <input type="password" class="form-control" id="newpass">
                    </div>
                </div>
                <button type="submit" class="btn btn-primary">Submit</button>
            </form> 
            <h5>Trocar imagem</h5>
            <hr>
            <form action="/uploadImagemEsp" method="POST" enctype="multipart/form-data">
                <input type="file" name="image">
                <input type="submit" value="Upload">
            </form>


        </div>
    </div>
</div>