<div class="container mt-5 d-flex justify-content-center">
    <table class="tabelas"  style="width: 1000px;">
        <thead>
            <tr>
                <th>Garantia</th>
                <th>Entrega</th>
                <th>Estado</th>
                <th >Nome dos Pedidos</th>
                <th>Lucro</th>
                <th>Lauda</th>
                <th>Pago</th>
                <th>Info</th>
                <th>Chat</th>
                <th>Opções</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach($this->view->pedidos as $pedido_arr => $pedido) { ?>
                <tr>
                    <td><?= $pedido['prazo_garantia'] ?></td>
                    <td><?= $pedido['prazo_entrega'] ?></td>
                    <td class="status" value="<?= $pedido['status'] ?>"><?= $pedido['status'] ?></td>
                    <td class="titulo"><?= $pedido['titulo'] ?></td>
                    <td><?= $pedido['oferta'] ?></td>
                    <td><?= $pedido['paginas'] ?></td>
                    <td><?= $pedido['pagamento'] ?></td>
                    <td><a href="pedido_visu_esp?id=<?= $pedido['id'] ?>">Inf</td>
                    <td><a href="/esp/chat-pedido?id=<?= $pedido['id'] ?>&id_usuario=<?= $pedido['id_usuario'] ?>">Chat</a></td>
                    <td><?= $pedido['fonte'] ?></td>

                </tr>
            <?php } ?>
        </tbody>
    </table>
</div>

<script>


    function corStatus(){
        var cells = document.querySelectorAll('.status');

        for (var i = 0; i < cells.length; i++) {
            var cell = cells[i];

          // verifica se o conteúdo da célula é igual a 1 ou 2
            if (cell.innerHTML == '1') {
                cell.innerHTML = 'Novo';
                cell.classList.add('rosa'); 

            } else if (cell.innerHTML == '2') {
                cell.innerHTML = 'Fazendo';
                cell.classList.add('laranja'); 

            }else if (cell.innerHTML == '3') {
                cell.innerHTML = 'Entregue';
                cell.classList.add('azul-claro'); 

            }else if(cell.innerHTML == '4') {
                cell.innerHTML = 'Garantia';
                cell.classList.add('azul'); 
                
            }else if(cell.innerHTML == '5') {
                cell.innerHTML = 'Revisar';
                cell.classList.add('vermelho');

            }else if(cell.innerHTML == '6') {
                cell.innerHTML = 'Pago';
                cell.classList.add('verde');
            }
        }
    }



    



    corStatus()



</script>
