<div class="container mt-3">
    <table class="tabelas">
        <thead>
            <tr>
                <th>Garantia</th>
                <th>Entrega</th>
                <th>Estado</th>
                <th >Nome dos Pedidos</th>
                <th>Lucro</th>
                <th>Lauda</th>
                <th>Pago</th>
                <th>Info</th>
                <th>Chat</th>
                <th>Opções</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach($this->view->pedidos as $pedido_arr => $pedido) { ?>
                <tr>
                    <td><?= $pedido['prazo_garantia'] ?></td>
                    <td><?= $pedido['prazo_entrega'] ?></td>
                    <td class="status" value="<?= $pedido['status'] ?>"><?= $pedido['status'] ?></td>
                    <td class="titulo"><?= $pedido['titulo'] ?></td>
                    <td><?= $pedido['oferta'] ?></td>
                    <td><?= $pedido['paginas'] ?></td>
                    <td><?= $pedido['pagamento'] ?></td>
                    <td><a href="pedido_visu_esp?id=<?= $pedido['id'] ?>">Inf</td>
                    <td><?= $pedido['fonte'] ?></td>
                    <td><?= $pedido['fonte'] ?></td>

                </tr>
            <?php } ?>
        </tbody>
    </table>
</div>

<script>

    function manipularEntrega(){
        var cells = document.querySelectorAll('.entrega');

        // percorre todas as células da tabela
        for (var i = 0; i < cells.length; i++) {
            var cell = cells[i];

        // verifica se o conteúdo da célula é igual a 1 ou 2
            if (cell.innerHTML == '1') {
                cell.innerHTML = 'N'; // substitui por "N"
                cell.classList.add('n'); // adiciona classe "n"
            } else if (cell.innerHTML == '2') {
                cell.innerHTML = 'S'; // substitui por "S"
                cell.classList.add('s'); // adiciona classe "s"
            }
        }
    }

    function corStatus(){
        var cells = document.querySelectorAll('.status');

        for (var i = 0; i < cells.length; i++) {
            var cell = cells[i];

          // verifica se o conteúdo da célula é igual a 1 ou 2
            if (cell.innerHTML == '0') {
                cell.innerHTML = 'Novo';
                cell.classList.add('rosa'); 

            } else if (cell.innerHTML == '1') {
                cell.innerHTML = 'Aceito';
                cell.classList.add('laranja'); 

            }else if (cell.innerHTML == '2') {
                cell.innerHTML = 'Entregue';
                cell.classList.add('azul'); 

            }else if(cell.innerHTML == '3') {
                cell.innerHTML = 'Revisar';
                cell.classList.add('vermelho'); 
                
            }else if(cell.innerHTML == '4') {
                cell.innerHTML = 'Pago';
                cell.classList.add('verde');
            }
        }
    }



    


    manipularEntrega()
    corStatus()



</script>
