<?php 

$pedido = $this->view->pedidos;

?>


<div class="container mt-4 meio justify-content-center">
    <div class="row justify-content-between">
        <div class="col-8">
            <p>Oferta:</p>
        </div> 
        <div class="col-4"> 
           <p> R$ <?= $pedido['oferta'] ?></p>
        </div>
    </div>

    <div class="row justify-content-between">
        <div class="col-8">
            <p>N de pag:</p>
        </div> 
        <div class="col-4"> 
           <p><?= $pedido['paginas'] ?></p>
        </div>
    </div>

    <div class="row justify-content-between">
        <div class="col-8">
            <p>Data de entrega:</p>
        </div> 
        <div class="col-4"> 
           <p><?= $pedido['prazo_entrega'] ?></p>
        </div>
    </div>
    
    <div class="row justify-content-between">
        <div class="col-8">
            <p>Disciplina:</p>
        </div> 
        <div class="col-4"> 
           <p><?= $pedido['disciplina'] ?></p>
        </div>
    </div>

    <div class="row justify-content-between">
        <div class="col-8">
            <p>Tipo de trabalho:</p>
        </div> 
        <div class="col-4"> 
           <p><?= $pedido['tipo'] ?></p>
        </div>
    </div>

    <div class="row justify-content-between">
        <div class="col-8">
            <p>Metodologia:</p>
        </div> 
        <div class="col-4"> 
           <p><?= $pedido['metodologia'] ?></p>
        </div>
    </div>

    <div class="row justify-content-between">
        <div class="col-8">
            <p>Garantia:</p>
        </div> 
        <div class="col-4"> 
           <p><?= $pedido['prazo_garantia'] ?></p>
        </div>
    </div>

    <div class="row justify-content-between">
        <div class="col-8">
            <p>Observações:</p>
        </div> 
        <div class="col-4"> 
           <p><?= $pedido['observacao'] ?></p>
        </div>
    </div>

    <div class="row justify-content-between">
        <div class="col-8">
            <p>Tema:</p>
        </div> 
        <div class="col-4"> 
           <p><?= $pedido['titulo'] ?></p>
        </div>
    </div>

    Estrutura do artigo ########################

    <div class="row justify-content-between">
        <div class="col-12">
        <p><?= $pedido['corpo'] ?></p>
        </div> 
    </div>

    <?php 
        $valor_coluna = $pedido['status'];

        if ($valor_coluna == 0 ) { ?>
            
            <form method="post" action="/esp/aceita_pedido">
                <input type="hidden" name="id" value="<?= $pedido['id'] ?>">
                <p>Aceita o serviço?</p>
                <button type="submit" name="aceita" onclick="confirmar()" value="1">Sim</button>
                <button type="submit" name="aceita" onclick="confirmar()" value="2">Não</button>
                <a ><?= $pedido['id'] ?></a>
            </form>
    <?php }else if($valor_coluna == 2) {?>
            --  
    <?php } ?>
</div>


<script>
    function confirmar() {
            if (confirm("tem certeza?")) {
                // Se o usuário confirmar, realizar a ação desejada
                // Exemplo: enviar uma requisição AJAX para o servidor para apagar um registro
            }
        }
</script>

