<div class="container mt-3">
    <table class="tabelas">
        <thead>
            <tr>
                <th>Garantia</th>
                <th>Entrega</th>
                <th>Entregue</th>
                <th>Estado</th>
                <th >Nome dos Pedidos</th>
                <th>Lucro</th>
                <th>Lauda</th>
                <th>Pago</th>
                <th>Info</th>
                <th>Chat</th>
                <th>Opções</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach($this->view->pedidos as $pedido_arr => $pedido) { ?>
                <tr>
                    <td><?= $pedido['prazo_garantia'] ?></td>
                    <td><?= $pedido['prazo_entrega'] ?></td>
                    <td class="entrega"><?= $pedido['entregue'] ?></td>
                    <td class="status" value="<?= $pedido['status'] ?>"><?= $pedido['status'] ?></td>
                    <td class="titulo"><?= $pedido['titulo'] ?></td>
                    <td><?= $pedido['oferta'] ?></td>
                    <td><?= $pedido['paginas'] ?></td>
                    <td><?= $pedido['pagamento'] ?></td>
                    <td><?= $pedido['id'] ?></td>
                    <td><?= $pedido['fonte'] ?></td>
                    <td><?= $pedido['fonte'] ?></td>
                    <td>
                        <?php 
                            $valor_coluna = $pedido['status'];

                            if ($valor_coluna == 0 ) { ?>
                                
                                <form method="post" action="/esp/aceita_pedido">
                                    <input type="hidden" name="id" value="<?= $pedido['id'] ?>">
                                    <p>Aceita o serviço?</p>
                                    <button type="submit" name="aceita" onclick="confirmar()" value="1">Sim</button>
                                    <button type="submit" name="aceita" onclick="confirmar()" value="2">Não</button>
                                    <a ><?= $pedido['id'] ?></a>
                                </form>
                        <?php }else if($valor_coluna == 2) {?>
                                --  
                        <?php } ?>
                        
                    </td>
                </tr>
            <?php } ?>
        </tbody>
    </table>
</div>

<script>

    function manipularEntrega(){
        var cells = document.querySelectorAll('.entrega');

        // percorre todas as células da tabela
        for (var i = 0; i < cells.length; i++) {
            var cell = cells[i];

        // verifica se o conteúdo da célula é igual a 1 ou 2
            if (cell.innerHTML == '1') {
                cell.innerHTML = 'N'; // substitui por "N"
                cell.classList.add('n'); // adiciona classe "n"
            } else if (cell.innerHTML == '2') {
                cell.innerHTML = 'S'; // substitui por "S"
                cell.classList.add('s'); // adiciona classe "s"
            }
        }
    }

    function corStatus(){
        var cells = document.querySelectorAll('.status');

        for (var i = 0; i < cells.length; i++) {
            var cell = cells[i];

        // verifica se o conteúdo da célula é igual a 1 ou 2
            if (cell.innerHTML == '2') {
                cell.classList.add('azul'); // adiciona classe "n"
            } else if (cell.innerHTML == '3') {
                cell.classList.add('s'); // adiciona classe "s"
            }else if (cell.innerHTML == '4') {
                cell.classList.add('vermelho'); // adiciona classe "s"
            }
        }
    }


    function confirmar() {
        if (confirm("tem certeza?")) {
            // Se o usuário confirmar, realizar a ação desejada
            // Exemplo: enviar uma requisição AJAX para o servidor para apagar um registro
        }
    }

    


    manipularEntrega()
    corStatus()



</script>
