<div class="lista-lateral">
		<div class="foto">
			    <?php foreach($this->view->usuario as $usuario_arr => $usuario) { ?>
                	<img src=" <?= $usuario['path_imagem'] ?> " style="width: 100px;" alt="Imagem do usuário">
				<?php } ?>

		</div>
		<ul class="form-lateral">
			<li class="lista principal"><a class="link" href="/esp/home">Home</a></li>
			<li hr class="lista principal"><a class="link" href="/esp/pedidos">Pedidos</a></li>
			<li class="lista principal">Mensagens</li>
			<li class="lista principal"><a class="link" href="/esp/calendario">Calendario</a></li>
		</ul>
</div>