<html>

<head>
	<meta charset="utf-8" />
	<title>Projeto A</title>
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet"
		integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
	<script src="https://kit.fontawesome.com/2621a537e3.js" crossorigin="anonymous"></script>
	<link rel="stylesheet" href="/css/style.css" />

</head>

<body>
<?php

if (!isset($_SESSION)) 
{
    session_start();
	
    if($_SESSION['tipo'] != 2){
        header('Location: /');  
    }
}


?>
	<nav class="navbar navbar-expand-lg bg-dark-subtle shadow" style="height:60px">
	<div class="container-fluid">
		<a class="navbar-brand" href="/adm/home">SUPER TCC	</a>
		<div class="collapse navbar-collapse">
			<div class="navbar-nav">
				<a class="nav-link" href="/esp/home">Home</a>

				<a class="nav-link" href="#">Mensagens</a>

				<a class="nav-link" href="#">Meu Perfil</a>
			</div>
		</div>
		<div class="collapse navbar-collapse justify-content-end">	
			<div class="navbar-nav">
				<a class="nav-link" href="/configurar"><img style="width:30px" src="/img/user.png">&nbsp;<?php echo $_SESSION['nome'] ?></a>&nbsp;&nbsp;&nbsp;&nbsp;
				<a type="button" class="button" href="/sair">Sair</a>
			</div>
		</div>
	</div>
	</nav>

	<div class="lista-lateral">
		<div class="foto">

		</div>
		<ul class="form-lateral">
			<li class="lista principal">Home</li>
			<li class="lista principal">Pedidos</li>
			<li class="lista principal">Mensagens</li>
			<li class="lista principal">Calendario</li>
		</ul>
	</div>

	<div style="position:absolute;left: 170px">
	<?= $this->content() ?>
	</div>



	<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"
		integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN"
		crossorigin="anonymous">
	</script>
</body>

</html>