<html>

<head>
	<meta charset="utf-8" />
	<title>Projeto A</title>
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet"
		integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
	<script src="https://kit.fontawesome.com/2621a537e3.js" crossorigin="anonymous"></script>
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.0/jquery.min.js"></script>
	<link rel="stylesheet" href="/css/style.css" />



</head>

<body>
<?php


if (!isset($_SESSION)) 
{
    session_start();
	
    if($_SESSION['tipo'] != 2){
        header('Location: /');  
    }
}
?>

<nav class="navbar navbar-expand-lg bg-dark-subtle shadow" style="height:60px">
		<div class="container-fluid">
			<a class="navbar-brand" href="/esp/home">SUPER TCC	</a>
			<div class="collapse navbar-collapse justify-content-end">	
				<div class="navbar-nav">
					<a class="nav-link" href="/esp/configurar"><img style="width:30px" src="/img/user.png">&nbsp;<?php echo $_SESSION['nome'] ?></a>&nbsp;&nbsp;&nbsp;&nbsp;
					<a type="button" class="button" href="/sair">Sair</a>
				</div>
			</div>
		</div>
</nav>

<div class="lista-lateral">
		<div class="foto">
			<img src="/<?php echo $_SESSION['path_imagem'] ?>" style="width: 140px;" alt="Imagem do usuário">
		</div>
		<ul class="form-lateral">
			<li class="lista principal"><a class="link" href="/esp/home">Home</a></li>
			<li hr class="lista principal" ><a class="link" href="/esp/pedidos">Pedidos</a></li>
			<li class="lista principal">Mensagens</li>
			<li class="lista principal"><a class="link" href="/esp/calendario" id="calendario">Calendario</a></li>
		</ul>
</div>


	<?= $this->content() ?>




	<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"
		integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN"
		crossorigin="anonymous">
	</script>
</body>

</html>